CXX = dpcpp-cl
CXXFLAGS = /O2 /EHsc /Zi
LDFLAGS = 
EXE_NAME = bitonic-sort.exe
SOURCES = src/bitonic-sort.cpp

USM_EXE_NAME = bitonic-sort.exe
USM_SOURCES = src/bitonic-sort.cpp

all: main

main:
	$(CXX) $(CXXFLAGS) -o $(EXE_NAME) $(SOURCES) $(LDFLAGS)

build_usm:
	$(CXX) $(CXXFLAGS) -o $(USM_EXE_NAME) $(USM_SOURCES) $(LDFLAGS)

run: 
	$(EXE_NAME)

run_usm: 
	$(USM_EXE_NAME)

clean: 
	del /F /Q *.ilk *.pdb $(EXE_NAME) $(USM_EXE_NAME)
