CXX = dpcpp-cl
CXXFLAGS = /O2 /EHsc /Zi
LDFLAGS = 
EXE_NAME = bitonic-sort.exe
SOURCES = src/bitonic-sort.cpp

all: main

main:
	$(CXX) $(CXXFLAGS) -o $(EXE_NAME) $(SOURCES) $(LDFLAGS)

run: 
	$(EXE_NAME)

clean: 
	del /F /Q *.ilk *.pdb $(EXE_NAME)
